[color-theme]
name = "Light+"
color-preference = "light"

[color-theme.base]
white = ""
black = ""
grey = ""
blue = ""
red = ""
yellow = ""
orange = ""
green = ""
purple = ""
cyan = ""
magenta = ""

[color-theme.syntax]
attribute = ""
builtinType = ""
comment = "#008000"
constant = "#0000FF"
constructor = ""
embedded = ""
enum = "#267F99"
enum-member = "#0070C1"
enumMember = "#0070C1"
escape = ""
field = ""
function = "#795E26"
"function.method" = ""
interface = "#267F99"
keyword = "#0000FF"
label = ""
method = "#795e26"
number = "#098658"
property = "#001080"
"punctuation.delimiter" = ""
selfKeyword = "#0000FF"
string = "#A31515"
"string.escape" = ""
struct = "#267F99"
structure = ""
symbol = ""
tag = ""
"text.reference" = ""
"text.title" = ""
"text.uri" = ""
type = ""
"type.builtin" = ""
typeAlias = "#267f99"
variable = "#001080"
"variable.other.member" = ""

[color-theme.ui]
"activity.background" = "#303031"
"activity.current" = ""
"completion.background" = "#1e1e1e"
"completion.current" = ""
"editor.background" = "#FFFFFF"
"editor.caret" = ""
"editor.current_line" = "#FFFFFF11"
"editor.dim" = "#6F6F6F"
"editor.focus" = "#cccccc"
"editor.sticky_header_background" = "#bad3e6"
"editor.foreground" = "#616161"
"editor.link" = "#006ab1"
"editor.selection" = "#add6ff"
"error_lens.error.background" = ""
"error_lens.error.foreground" = "#E51400"
"error_lens.other.background" = ""
"error_lens.other.foreground" = ""
"error_lens.warning.background" = ""
"error_lens.warning.foreground" = "#BF8803"
"hover.background" = "#252526"
"inlay_hint.background" = "#c4c4c44d"
"inlay_hint.foreground" = "#333333cc"
"lapce.active_tab" = "#FFFFFF"
"lapce.border" = "#cccccc33"
"lapce.dropdown_shadow" = ""
"lapce.error" = "#e51400"
"lapce.inactive_tab" = "#ECECEC"
"lapce.scroll_bar" = "#343434"
"lapce.warn" = "#BF8803"
"markdown.blockquote" = ""
"palette.background" = "#252526"
"palette.current" = "#04395E"
"panel.background" = "#F3F3F3"
"panel.current" = "#0060C0"
"panel.hovered" = "#E8E8E8"
"source_control.added" = "#81b88b"
"source_control.modified" = "#e2c08d"
"source_control.removed" = "#c74e39"
"status.background" = "#007acc"
"status.modal.insert" = ""
"status.modal.normal" = ""
"status.modal.terminal" = ""
"status.modal.visual" = ""
"terminal.background" = "#ffffff"
"terminal.black" = "#000000"
"terminal.blue" = "#2472c8"
"terminal.bright_black" = "#666666"
"terminal.bright_blue" = "#3b8eea"
"terminal.bright_cyan" = "#29b8db"
"terminal.bright_green" = "#23d18b"
"terminal.bright_magenta" = "#d670d6"
"terminal.bright_red" = "#f14c4c"
"terminal.bright_white" = "#e5e5e5"
"terminal.bright_yellow" = "#f5f543"
"terminal.cursor" = "$white"
"terminal.cyan" = "#11a8cd"
"terminal.foreground" = "#333333"
"terminal.green" = "#0dbc79"
"terminal.magenta" = "#bc3fbc"
"terminal.red" = "#cd3131"
"terminal.white" = "#e5e5e5"
"terminal.yellow" = "#e5e510"

[ui]
font-family = ""
font-size = 12
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
